const general = [
  { id: "1", tag: "啊啊", entry: "w(ﾟДﾟ)w" },
  { id: "2", tag: "擦眼泪", entry: "(ノへ￣、)" },
  { id: "6", tag: "不屑", entry: "(￣_,￣ )" },
  { id: "12", tag: "好耶", entry: "ヽ(✿ﾟ▽ﾟ)ノ" },
  { id: "5", tag: "棒", entry: "(๑•̀ㅂ•́)و✧" },
  { id: "10", tag: "抽", entry: "(￣ε(#￣)☆╰╮o(￣皿￣///) " },
  { id: "51", tag: "亲", entry: "（づ￣3￣）づ╭❤～" },
  { id: "59", tag: "汗", entry: "Σ( ° △ °|||)︴" },
  { id: "4", tag: "笨", entry: "(～￣(OO)￣)ブ " },
  { id: "7", tag: "擦", entry: "凸(艹皿艹 ) " },
  { id: "8", tag: "啵啵", entry: "(* ￣3)(ε￣ *) " },
  { id: "9", tag: "挖鼻屎", entry: "(*￣rǒ￣)" },
  { id: "11", tag: "嗷", entry: "┗|｀O′|┛ 嗷~~ " },
  { id: "13", tag: "乐", entry: "φ(≧ω≦*)♪ " },
  { id: "14", tag: "飞", entry: "︿(￣︶￣)︿" },
  { id: "15", tag: "好滴", entry: "(u‿ฺu✿ฺ)" },
  { id: "16", tag: "hi", entry: "Hi~ o(*￣▽￣*)ブ " },
  { id: "17", tag: "啦啦", entry: "♪(^∇^*)" },
  { id: "18", tag: "拍桌", entry: "o(*≧▽≦)ツ┏━┓" },
  { id: "19", tag: "惊喜", entry: "╰(*°▽°*)╯" },
  { id: "20", tag: "嘟嘴", entry: "（○｀ 3′○）" },
  { id: "21", tag: "乖", entry: "o(*^＠^*)o " },
  { id: "22", tag: "喂", entry: "(#`O′) " },
  { id: "23", tag: "愣住", entry: "(°ー°〃) " },
  { id: "24", tag: "放屁", entry: "○|￣|_ =3 " },
  { id: "25", tag: "哼哼", entry: "o(￣ヘ￣o＃) " },
  { id: "26", tag: "可恶", entry: "（＝。＝）" },
  { id: "27", tag: "切", entry: "~~( ﹁ ﹁ ) ~~~ " },
  { id: "28", tag: "去", entry: "(ーー゛)" },
  { id: "29", tag: "生气", entry: "(ー`´ー)" },
  { id: "30", tag: "喂", entry: "(#`O′) " },
  { id: "31", tag: "怨念", entry: "o(一︿一+)o " },
  { id: "32", tag: "崩溃", entry: "o(≧口≦)o " },
  { id: "33", tag: "不是我", entry: "ㄟ( ▔, ▔ )ㄏ " },
  { id: "34", tag: "败了", entry: "(o_ _)ﾉ" },
  { id: "35", tag: "呃呃呃", entry: "(⊙﹏⊙) " },
  { id: "36", tag: "切", entry: "(ˉ▽￣～) 切~~ " },
  { id: "37", tag: "无言", entry: "（＊￣（エ）￣）" },
  { id: "38", tag: "摊手", entry: "┑(￣Д ￣)┍" },
  { id: "39", tag: "不懂", entry: "(＠_＠;)" },
  { id: "40", tag: "呆", entry: "━┳━　━┳━ " },
  { id: "41", tag: "扶额", entry: "(☆´益`)c" },
  { id: "42", tag: "囧", entry: "（´Д`）" },
  { id: "43", tag: "投降", entry: "┗( T﹏T )┛" },
  { id: "44", tag: "我错了", entry: "(。﹏。*) " },
  { id: "45", tag: "喵星人", entry: "o( =•ω•= )m " },
  { id: "46", tag: "喵呜", entry: "≡ω≡" },
  { id: "47", tag: "熊", entry: "(*￣(エ)￣) " },
  { id: "48", tag: "害羞", entry: "(✿◡‿◡)" },
  { id: "49", tag: "脸红", entry: "(*/ω＼*)" },
  { id: "50", tag: "呜呜呜", entry: "┭┮﹏┭┮" },
  { id: "52", tag: "拜", entry: "ヾ(￣▽￣)Bye~Bye~ " },
  { id: "53", tag: "斜眼", entry: "( ﹁ ﹁ ) ~→ " },
  { id: "54", tag: "美味", entry: "Ψ(￣∀￣)Ψ" },
  { id: "55", tag: "闪", entry: "✧(≖ ◡ ≖✿)" },
  { id: "56", tag: "淡定", entry: "━━(￣ー￣*|||━━" },
  { id: "57", tag: "太可怕了", entry: "ヽ(*。>Д<)o゜ " },
  { id: "58", tag: "恐怖", entry: "┌(。Д。)┐" },
  { id: "60", tag: "orz", entry: "○|￣|_" },
  { id: "61", tag: "good", entry: "o(￣▽￣)ｄ " },
  { id: "62", tag: "伤心", entry: "(；′⌒`) " },
  { id: "63", tag: "糟糕", entry: "X﹏X" },
  { id: "472", tag: "圣诞", entry: "*<|:-) " }
];

export default general;
