"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const mou = [
    { id: "135", tag: "嗷", entry: "(>▽<)" },
    { id: "136", tag: "嗷", entry: "ヾ(≧O≦)〃嗷~ " },
    { id: "137", tag: "嗷", entry: "┗|｀O′|┛ 嗷~~ " },
    { id: "139", tag: "笨", entry: "(～￣(OO)￣)ブ " },
    { id: "138", tag: "笨蛋", entry: "(っ*´Д`)っ" },
    { id: "140", tag: "笨人", entry: "ヾ(´∀`o)+" },
    { id: "141", tag: "表", entry: "<(￣3￣)> 表！ " },
    { id: "142", tag: "不要啊", entry: "不＞(￣ε￣ = ￣3￣)<要" },
    { id: "143", tag: "蹭", entry: "( *￣▽￣)((≧︶≦*)" },
    { id: "144", tag: "等等", entry: "...(*￣０￣)ノ[等等我…]" },
    { id: "145", tag: "嘟嘴", entry: "o(￣ε￣*) " },
    { id: "146", tag: "嘟嘴", entry: "（○｀ 3′○）" },
    { id: "147", tag: "乖", entry: "o(*^＠^*)o " },
    { id: "148", tag: "鬼脸", entry: "(￣┰￣*) " },
    { id: "149", tag: "滚", entry: "(～o￣▽￣)～o 。。。滚来滚去……o～(＿△＿o～) ~。。。 " },
    { id: "150", tag: "好可爱", entry: "（*＾-＾*）" },
    { id: "151", tag: "好喜欢", entry: "(≧∇≦)ﾉ" },
    { id: "152", tag: "坏人", entry: "～(　TロT)σ " },
    { id: "153", tag: "呼唤", entry: "(/0￣)o [呼唤] " },
    { id: "154", tag: "可爱", entry: "n(*≧▽≦*)n " },
    { id: "155", tag: "来啦", entry: "(～o￣▽￣)～o ~。。。 " },
    { id: "156", tag: "卖萌", entry: "=￣ω￣=" },
    { id: "157", tag: "满意", entry: "（´v｀）" },
    { id: "172", tag: "媚眼", entry: "ο(=•ω＜=)ρ⌒☆" },
    { id: "158", tag: "捏脸", entry: "<( ‵□′)───C＜─___-)||" },
    { id: "159", tag: "你好", entry: "ヾ(´･ω･｀)ﾉ" },
    { id: "160", tag: "你回来啦", entry: "ヾ(^▽^*))) " },
    { id: "161", tag: "哦", entry: "ｍ(o・ω・o)ｍ" },
    { id: "162", tag: "跑", entry: "ε = = (づ′▽`)づ " },
    { id: "163", tag: "飘", entry: "(～o￣3￣)～ " },
    { id: "177", tag: "弱", entry: "(。・・)ノ" },
    { id: "164", tag: "讨厌", entry: "(ノω<。)ノ))☆.。" },
    { id: "176", tag: "thx", entry: "☆⌒(*＾-゜)v THX!!" },
    { id: "165", tag: "偷看", entry: "(/ω＼*)……… (/ω•＼*) " },
    { id: "166", tag: "偷窥", entry: "┬┴┤_•) " },
    { id: "167", tag: "推到", entry: "(ﾉ*･ω･)ﾉ" },
    { id: "168", tag: "吐舌头", entry: "(￣┰￣*) " },
    { id: "178", tag: "喂", entry: "(#`O′) " },
    { id: "169", tag: "无辜", entry: "（o´・ェ・｀o）" },
    { id: "170", tag: "谢", entry: "谢啦!!☆⌒(*＾-゜)v " },
    { id: "171", tag: "欣慰", entry: "( ╯▽╰)" },
    { id: "173", tag: "真哒", entry: "o(〃'▽'〃)o " },
    { id: "174", tag: "猪", entry: "^(*￣(oo)￣)^ " },
    { id: "175", tag: "做梦", entry: "ZZzz…(。-ω-)..ooO((【•:*:~夢~:*:•】))" }
];
exports.default = mou;
