const foods = [
    { emoji: "🍏", alias: ":green_apple:", name: "GREEN APPLE" },
    { emoji: "🍎", alias: ":apple:", name: "RED APPLE" },
    { emoji: "🍐", alias: ":pear:", name: "PEAR" },
    { emoji: "🍊", alias: ":tangerine:", name: "TANGERINE" },
    { emoji: "🍋", alias: ":lemon:", name: "LEMON" },
    { emoji: "🍌", alias: ":banana:", name: "BANANA" },
    { emoji: "🍉", alias: ":watermelon:", name: "WATERMELON" },
    { emoji: "🍇", alias: ":grapes:", name: "GRAPES" },
    { emoji: "🍓", alias: ":strawberry:", name: "STRAWBERRY" },
    { emoji: "🍈", alias: ":melon:", name: "MELON" },
    { emoji: "🍒", alias: ":cherries:", name: "CHERRIES" },
    { emoji: "🍑", alias: ":peach:", name: "PEACH" },
    { emoji: "🍍", alias: ":pineapple:", name: "PINEAPPLE" },
    { emoji: "🥝", alias: ":kiwi_fruit:", name: "KIWIFRUIT" },
    { emoji: "🥑", alias: ":avocado:", name: "AVOCADO" },
    { emoji: "🍅", alias: ":tomato:", name: "TOMATO" },
    { emoji: "🍆", alias: ":eggplant:", name: "AUBERGINE" },
    { emoji: "🥒", alias: ":cucumber:", name: "CUCUMBER" },
    { emoji: "🥕", alias: ":carrot:", name: "CARROT" },
    { emoji: "🌽", alias: ":corn:", name: "EAR OF MAIZE" },
    { emoji: "🌶", alias: ":hot_pepper:", name: "HOT PEPPER" },
    { emoji: "🥔", alias: ":potato:", name: "POTATO" },
    { emoji: "🍠", alias: ":sweet_potato:", name: "ROASTED SWEET POTATO" },
    { emoji: "🌰", alias: ":chestnut:", name: "CHESTNUT" },
    { emoji: "🥜", alias: ":peanuts:", name: "PEANUTS" },
    { emoji: "🍯", alias: ":honey_pot:", name: "HONEY POT" },
    { emoji: "🥐", alias: ":croissant:", name: "CROISSANT" },
    { emoji: "🍞", alias: ":bread:", name: "BREAD" },
    { emoji: "🥖", alias: ":baguette_bread:", name: "BAGUETTE BREAD" },
    { emoji: "🧀", alias: ":cheese:", name: "CHEESE WEDGE" },
    { emoji: "🥚", alias: ":egg:", name: "EGG" },
    { emoji: "🍳", alias: ":fried_egg:", name: "COOKING" },
    { emoji: "🥓", alias: ":bacon:", name: "BACON" },
    { emoji: "🥞", alias: ":pancakes:", name: "PANCAKES" },
    { emoji: "🍤", alias: ":fried_shrimp:", name: "FRIED SHRIMP" },
    { emoji: "🍗", alias: ":poultry_leg:", name: "POULTRY LEG" },
    { emoji: "🍖", alias: ":meat_on_bone:", name: "MEAT ON BONE" },
    { emoji: "🍕", alias: ":pizza:", name: "SLICE OF PIZZA" },
    { emoji: "🌭", alias: ":hotdog:", name: "HOT DOG" },
    { emoji: "🍔", alias: ":hamburger:", name: "HAMBURGER" },
    { emoji: "🍟", alias: ":fries:", name: "FRENCH FRIES" },
    { emoji: "🥙", alias: ":stuffed_flatbread:", name: "STUFFED FLATBREAD" },
    { emoji: "🌮", alias: ":taco:", name: "TACO" },
    { emoji: "🌯", alias: ":burrito:", name: "BURRITO" },
    { emoji: "🥗", alias: ":green_salad:", name: "GREEN SALAD" },
    {
        emoji: "🥘",
        alias: ":shallow_pan_of_food:",
        name: "SHALLOW PAN OF FOOD"
    },
    { emoji: "🍝", alias: ":spaghetti:", name: "SPAGHETTI" },
    { emoji: "🍜", alias: ":ramen:", name: "STEAMING BOWL" },
    { emoji: "🍲", alias: ":stew:", name: "POT OF FOOD" },
    { emoji: "🍥", alias: ":fish_cake:", name: "FISH CAKE WITH SWIRL DESIGN" },
    { emoji: "🍣", alias: ":sushi:", name: "SUSHI" },
    { emoji: "🍱", alias: ":bento:", name: "BENTO BOX" },
    { emoji: "🍛", alias: ":curry:", name: "CURRY AND RICE" },
    { emoji: "🍚", alias: ":rice:", name: "COOKED RICE" },
    { emoji: "🍙", alias: ":rice_ball:", name: "RICE BALL" },
    { emoji: "🍘", alias: ":rice_cracker:", name: "RICE CRACKER" },
    { emoji: "🍢", alias: ":oden:", name: "ODEN" },
    { emoji: "🍡", alias: ":dango:", name: "DANGO" },
    { emoji: "🍧", alias: ":shaved_ice:", name: "SHAVED ICE" },
    { emoji: "🍨", alias: ":ice_cream:", name: "ICE CREAM" },
    { emoji: "🍦", alias: ":icecream:", name: "SOFT ICE CREAM" },
    { emoji: "🍰", alias: ":cake:", name: "SHORTCAKE" },
    { emoji: "🎂", alias: ":birthday:", name: "BIRTHDAY CAKE" },
    { emoji: "🍮", alias: ":custard:", name: "CUSTARD" },
    { emoji: "🍭", alias: ":lollipop:", name: "LOLLIPOP" },
    { emoji: "🍬", alias: ":candy:", name: "CANDY" },
    { emoji: "🍫", alias: ":chocolate_bar:", name: "CHOCOLATE BAR" },
    { emoji: "🍿", alias: ":popcorn:", name: "POPCORN" },
    { emoji: "🍩", alias: ":doughnut:", name: "DOUGHNUT" },
    { emoji: "🍪", alias: ":cookie:", name: "COOKIE" },
    { emoji: "🥛", alias: ":milk_glass:", name: "GLASS OF MILK" },
    { emoji: "🍼", alias: ":baby_bottle:", name: "BABY BOTTLE" },
    {
        emoji: "☕️",
        alias: ":coffee:",
        name: "HOT BEVERAGE, VARIATION SELECTOR-16"
    },
    { emoji: "🍵", alias: ":tea:", name: "TEACUP WITHOUT HANDLE" },
    { emoji: "🍶", alias: ":sake:", name: "SAKE BOTTLE AND CUP" },
    { emoji: "🍺", alias: ":beer:", name: "BEER MUG" },
    { emoji: "🍻", alias: ":beers:", name: "CLINKING BEER MUGS" },
    { emoji: "🥂", alias: ":clinking_glasses:", name: "CLINKING GLASSES" },
    { emoji: "🍷", alias: ":wine_glass:", name: "WINE GLASS" },
    { emoji: "🥃", alias: ":tumbler_glass:", name: "TUMBLER GLASS" },
    { emoji: "🍸", alias: ":cocktail:", name: "COCKTAIL GLASS" },
    { emoji: "🍹", alias: ":tropical_drink:", name: "TROPICAL DRINK" },
    { emoji: "🍾", alias: ":champagne:", name: "BOTTLE WITH POPPING CORK" },
    { emoji: "🥄", alias: ":spoon:", name: "SPOON" },
    { emoji: "🍴", alias: ":fork_and_knife:", name: "FORK AND KNIFE" },
    {
        emoji: "🍽",
        alias: ":plate_with_cutlery:",
        name: "FORK AND KNIFE WITH PLATE"
    }
];

export default foods;
