const objects = [
    { emoji: "⌚️", alias: ":watch:", name: "WATCH, VARIATION SELECTOR-16" },
    { emoji: "📱", alias: ":iphone:", name: "MOBILE PHONE" },
    {
        emoji: "📲",
        alias: ":calling:",
        name: "MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT"
    },
    { emoji: "💻", alias: ":computer:", name: "PERSONAL COMPUTER" },
    {
        emoji: "⌨️",
        alias: ":keyboard:",
        name: "KEYBOARD, VARIATION SELECTOR-16"
    },
    { emoji: "🖥", alias: ":desktop_computer:", name: "DESKTOP COMPUTER" },
    { emoji: "🖨", alias: ":printer:", name: "PRINTER" },
    { emoji: "🖱", alias: ":computer_mouse:", name: "THREE BUTTON MOUSE" },
    { emoji: "🖲", alias: ":trackball:", name: "TRACKBALL" },
    { emoji: "🕹", alias: ":joystick:", name: "JOYSTICK" },
    { emoji: "🗜", alias: ":clamp:", name: "COMPRESSION" },
    { emoji: "💽", alias: ":minidisc:", name: "MINIDISC" },
    { emoji: "💾", alias: ":floppy_disk:", name: "FLOPPY DISK" },
    { emoji: "💿", alias: ":cd:", name: "OPTICAL DISC" },
    { emoji: "📀", alias: ":dvd:", name: "DVD" },
    { emoji: "📼", alias: ":vhs:", name: "VIDEOCASSETTE" },
    { emoji: "📷", alias: ":camera:", name: "CAMERA" },
    { emoji: "📸", alias: ":camera_flash:", name: "CAMERA WITH FLASH" },
    { emoji: "📹", alias: ":video_camera:", name: "VIDEO CAMERA" },
    { emoji: "🎥", alias: ":movie_camera:", name: "MOVIE CAMERA" },
    { emoji: "📽", alias: ":film_projector:", name: "FILM PROJECTOR" },
    { emoji: "🎞", alias: ":film_strip:", name: "FILM FRAMES" },
    { emoji: "📞", alias: ":telephone_receiver:", name: "TELEPHONE RECEIVER" },
    {
        emoji: "☎️",
        alias: ":phone:",
        name: "BLACK TELEPHONE, VARIATION SELECTOR-16"
    },
    { emoji: "📟", alias: ":pager:", name: "PAGER" },
    { emoji: "📠", alias: ":fax:", name: "FAX MACHINE" },
    { emoji: "📺", alias: ":tv:", name: "TELEVISION" },
    { emoji: "📻", alias: ":radio:", name: "RADIO" },
    { emoji: "🎙", alias: ":studio_microphone:", name: "STUDIO MICROPHONE" },
    { emoji: "🎚", alias: ":level_slider:", name: "LEVEL SLIDER" },
    { emoji: "🎛", alias: ":control_knobs:", name: "CONTROL KNOBS" },
    { emoji: "⏱", alias: ":stopwatch:", name: "STOPWATCH" },
    { emoji: "⏲", alias: ":timer_clock:", name: "TIMER CLOCK" },
    { emoji: "⏰", alias: ":alarm_clock:", name: "ALARM CLOCK" },
    { emoji: "🕰", alias: ":mantelpiece_clock:", name: "MANTELPIECE CLOCK" },
    {
        emoji: "⌛️",
        alias: ":hourglass:",
        name: "HOURGLASS, VARIATION SELECTOR-16"
    },
    {
        emoji: "⏳",
        alias: ":hourglass_flowing_sand:",
        name: "HOURGLASS WITH FLOWING SAND"
    },
    { emoji: "📡", alias: ":satellite:", name: "SATELLITE ANTENNA" },
    { emoji: "🔋", alias: ":battery:", name: "BATTERY" },
    { emoji: "🔌", alias: ":electric_plug:", name: "ELECTRIC PLUG" },
    { emoji: "💡", alias: ":bulb:", name: "ELECTRIC LIGHT BULB" },
    { emoji: "🔦", alias: ":flashlight:", name: "ELECTRIC TORCH" },
    { emoji: "🕯", alias: ":candle:", name: "CANDLE" },
    { emoji: "🗑", alias: ":wastebasket:", name: "WASTEBASKET" },
    { emoji: "🛢", alias: ":oil_drum:", name: "OIL DRUM" },
    { emoji: "💸", alias: ":money_with_wings:", name: "MONEY WITH WINGS" },
    { emoji: "💵", alias: ":dollar:", name: "BANKNOTE WITH DOLLAR SIGN" },
    { emoji: "💴", alias: ":yen:", name: "BANKNOTE WITH YEN SIGN" },
    { emoji: "💶", alias: ":euro:", name: "BANKNOTE WITH EURO SIGN" },
    { emoji: "💷", alias: ":pound:", name: "BANKNOTE WITH POUND SIGN" },
    { emoji: "💰", alias: ":moneybag:", name: "MONEY BAG" },
    { emoji: "💳", alias: ":credit_card:", name: "CREDIT CARD" },
    { emoji: "💎", alias: ":gem:", name: "GEM STONE" },
    {
        emoji: "⚖️",
        alias: ":balance_scale:",
        name: "SCALES, VARIATION SELECTOR-16"
    },
    { emoji: "🔧", alias: ":wrench:", name: "WRENCH" },
    { emoji: "🔨", alias: ":hammer:", name: "HAMMER" },
    { emoji: "⚒", alias: ":hammer_and_pick:", name: "HAMMER AND PICK" },
    { emoji: "🛠", alias: ":hammer_and_wrench:", name: "HAMMER AND WRENCH" },
    { emoji: "⛏", alias: ":pick:", name: "PICK" },
    { emoji: "🔩", alias: ":nut_and_bolt:", name: "NUT AND BOLT" },
    { emoji: "⚙️", alias: ":gear:", name: "GEAR, VARIATION SELECTOR-16" },
    { emoji: "⛓", alias: ":chains:", name: "CHAINS" },
    { emoji: "🔫", alias: ":gun:", name: "PISTOL" },
    { emoji: "💣", alias: ":bomb:", name: "BOMB" },
    { emoji: "🔪", alias: ":hocho:", name: "HOCHO" },
    { emoji: "🗡", alias: ":dagger:", name: "DAGGER KNIFE" },
    {
        emoji: "⚔️",
        alias: ":crossed_swords:",
        name: "CROSSED SWORDS, VARIATION SELECTOR-16"
    },
    { emoji: "🛡", alias: ":shield:", name: "SHIELD" },
    { emoji: "🚬", alias: ":smoking:", name: "SMOKING SYMBOL" },
    { emoji: "⚰️", alias: ":coffin:", name: "COFFIN, VARIATION SELECTOR-16" },
    {
        emoji: "⚱️",
        alias: ":funeral_urn:",
        name: "FUNERAL URN, VARIATION SELECTOR-16"
    },
    { emoji: "🏺", alias: ":amphora:", name: "AMPHORA" },
    { emoji: "🔮", alias: ":crystal_ball:", name: "CRYSTAL BALL" },
    { emoji: "📿", alias: ":prayer_beads:", name: "PRAYER BEADS" },
    { emoji: "💈", alias: ":barber:", name: "BARBER POLE" },
    { emoji: "⚗️", alias: ":alembic:", name: "ALEMBIC, VARIATION SELECTOR-16" },
    { emoji: "🔭", alias: ":telescope:", name: "TELESCOPE" },
    { emoji: "🔬", alias: ":microscope:", name: "MICROSCOPE" },
    { emoji: "🕳", alias: ":hole:", name: "HOLE" },
    { emoji: "💊", alias: ":pill:", name: "PILL" },
    { emoji: "💉", alias: ":syringe:", name: "SYRINGE" },
    { emoji: "🌡", alias: ":thermometer:", name: "THERMOMETER" },
    { emoji: "🚽", alias: ":toilet:", name: "TOILET" },
    { emoji: "🚰", alias: ":potable_water:", name: "POTABLE WATER SYMBOL" },
    { emoji: "🚿", alias: ":shower:", name: "SHOWER" },
    { emoji: "🛁", alias: ":bathtub:", name: "BATHTUB" },
    { emoji: "🛀", alias: ":bath:", name: "BATH" },
    { emoji: "🛎", alias: ":bellhop_bell:", name: "BELLHOP BELL" },
    { emoji: "🔑", alias: ":key:", name: "KEY" },
    { emoji: "🗝", alias: ":old_key:", name: "OLD KEY" },
    { emoji: "🚪", alias: ":door:", name: "DOOR" },
    { emoji: "🛋", alias: ":couch_and_lamp:", name: "COUCH AND LAMP" },
    { emoji: "🛏", alias: ":bed:", name: "BED" },
    { emoji: "🛌", alias: ":sleeping_bed:", name: "SLEEPING ACCOMMODATION" },
    { emoji: "🖼", alias: ":framed_picture:", name: "FRAME WITH PICTURE" },
    { emoji: "🛍", alias: ":shopping:", name: "SHOPPING BAGS" },
    { emoji: "🛒", alias: ":shopping_cart:", name: "SHOPPING TROLLEY" },
    { emoji: "🎁", alias: ":gift:", name: "WRAPPED PRESENT" },
    { emoji: "🎈", alias: ":balloon:", name: "BALLOON" },
    { emoji: "🎏", alias: ":flags:", name: "CARP STREAMER" },
    { emoji: "🎀", alias: ":ribbon:", name: "RIBBON" },
    { emoji: "🎊", alias: ":confetti_ball:", name: "CONFETTI BALL" },
    { emoji: "🎉", alias: ":tada:", name: "PARTY POPPER" },
    { emoji: "🎎", alias: ":dolls:", name: "JAPANESE DOLLS" },
    { emoji: "🏮", alias: ":izakaya_lantern:", name: "IZAKAYA LANTERN" },
    { emoji: "🎐", alias: ":wind_chime:", name: "WIND CHIME" },
    { emoji: "✉️", alias: ":email:", name: "ENVELOPE, VARIATION SELECTOR-16" },
    {
        emoji: "📩",
        alias: ":envelope_with_arrow:",
        name: "ENVELOPE WITH DOWNWARDS ARROW ABOVE"
    },
    { emoji: "📨", alias: ":incoming_envelope:", name: "INCOMING ENVELOPE" },
    { emoji: "📧", alias: ":e-mail:", name: "E-MAIL SYMBOL" },
    { emoji: "💌", alias: ":love_letter:", name: "LOVE LETTER" },
    { emoji: "📥", alias: ":inbox_tray:", name: "INBOX TRAY" },
    { emoji: "📤", alias: ":outbox_tray:", name: "OUTBOX TRAY" },
    { emoji: "📦", alias: ":package:", name: "PACKAGE" },
    { emoji: "🏷", alias: ":label:", name: "LABEL" },
    {
        emoji: "📪",
        alias: ":mailbox_closed:",
        name: "CLOSED MAILBOX WITH LOWERED FLAG"
    },
    {
        emoji: "📫",
        alias: ":mailbox:",
        name: "CLOSED MAILBOX WITH RAISED FLAG"
    },
    {
        emoji: "📬",
        alias: ":mailbox_with_mail:",
        name: "OPEN MAILBOX WITH RAISED FLAG"
    },
    {
        emoji: "📭",
        alias: ":mailbox_with_no_mail:",
        name: "OPEN MAILBOX WITH LOWERED FLAG"
    },
    { emoji: "📮", alias: ":postbox:", name: "POSTBOX" },
    { emoji: "📯", alias: ":postal_horn:", name: "POSTAL HORN" },
    { emoji: "📜", alias: ":scroll:", name: "SCROLL" },
    { emoji: "📃", alias: ":page_with_curl:", name: "PAGE WITH CURL" },
    { emoji: "📄", alias: ":page_facing_up:", name: "PAGE FACING UP" },
    { emoji: "📑", alias: ":bookmark_tabs:", name: "BOOKMARK TABS" },
    { emoji: "📊", alias: ":bar_chart:", name: "BAR CHART" },
    {
        emoji: "📈",
        alias: ":chart_with_upwards_trend:",
        name: "CHART WITH UPWARDS TREND"
    },
    {
        emoji: "📉",
        alias: ":chart_with_downwards_trend:",
        name: "CHART WITH DOWNWARDS TREND"
    },
    { emoji: "🗒", alias: ":spiral_notepad:", name: "SPIRAL NOTE PAD" },
    { emoji: "🗓", alias: ":spiral_calendar:", name: "SPIRAL CALENDAR PAD" },
    { emoji: "📆", alias: ":calendar:", name: "TEAR-OFF CALENDAR" },
    { emoji: "📅", alias: ":date:", name: "CALENDAR" },
    { emoji: "📇", alias: ":card_index:", name: "CARD INDEX" },
    { emoji: "🗃", alias: ":card_file_box:", name: "CARD FILE BOX" },
    { emoji: "🗳", alias: ":ballot_box:", name: "BALLOT BOX WITH BALLOT" },
    { emoji: "🗄", alias: ":file_cabinet:", name: "FILE CABINET" },
    { emoji: "📋", alias: ":clipboard:", name: "CLIPBOARD" },
    { emoji: "📁", alias: ":file_folder:", name: "FILE FOLDER" },
    { emoji: "📂", alias: ":open_file_folder:", name: "OPEN FILE FOLDER" },
    {
        emoji: "🗂",
        alias: ":card_index_dividers:",
        name: "CARD INDEX DIVIDERS"
    },
    { emoji: "🗞", alias: ":newspaper_roll:", name: "ROLLED-UP NEWSPAPER" },
    { emoji: "📰", alias: ":newspaper:", name: "NEWSPAPER" },
    { emoji: "📓", alias: ":notebook:", name: "NOTEBOOK" },
    {
        emoji: "📔",
        alias: ":notebook_with_decorative_cover:",
        name: "NOTEBOOK WITH DECORATIVE COVER"
    },
    { emoji: "📒", alias: ":ledger:", name: "LEDGER" },
    { emoji: "📕", alias: ":closed_book:", name: "CLOSED BOOK" },
    { emoji: "📗", alias: ":green_book:", name: "GREEN BOOK" },
    { emoji: "📘", alias: ":blue_book:", name: "BLUE BOOK" },
    { emoji: "📙", alias: ":orange_book:", name: "ORANGE BOOK" },
    { emoji: "📚", alias: ":books:", name: "BOOKS" },
    { emoji: "📖", alias: ":book:", name: "OPEN BOOK" },
    { emoji: "🔖", alias: ":bookmark:", name: "BOOKMARK" },
    { emoji: "🔗", alias: ":link:", name: "LINK SYMBOL" },
    { emoji: "📎", alias: ":paperclip:", name: "PAPERCLIP" },
    { emoji: "🖇", alias: ":paperclips:", name: "LINKED PAPERCLIPS" },
    { emoji: "📐", alias: ":triangular_ruler:", name: "TRIANGULAR RULER" },
    { emoji: "📏", alias: ":straight_ruler:", name: "STRAIGHT RULER" },
    { emoji: "📌", alias: ":pushpin:", name: "PUSHPIN" },
    { emoji: "📍", alias: ":round_pushpin:", name: "ROUND PUSHPIN" },
    {
        emoji: "✂️",
        alias: ":scissors:",
        name: "BLACK SCISSORS, VARIATION SELECTOR-16"
    },
    { emoji: "🖊", alias: ":pen:", name: "LOWER LEFT BALLPOINT PEN" },
    { emoji: "🖋", alias: ":fountain_pen:", name: "LOWER LEFT FOUNTAIN PEN" },
    {
        emoji: "✒️",
        alias: ":black_nib:",
        name: "BLACK NIB, VARIATION SELECTOR-16"
    },
    { emoji: "🖌", alias: ":paintbrush:", name: "LOWER LEFT PAINTBRUSH" },
    { emoji: "🖍", alias: ":crayon:", name: "LOWER LEFT CRAYON" },
    { emoji: "📝", alias: ":memo:", name: "MEMO" },
    { emoji: "✏️", alias: ":pencil2:", name: "PENCIL, VARIATION SELECTOR-16" },
    { emoji: "🔍", alias: ":mag:", name: "LEFT-POINTING MAGNIFYING GLASS" },
    {
        emoji: "🔎",
        alias: ":mag_right:",
        name: "RIGHT-POINTING MAGNIFYING GLASS"
    },
    { emoji: "🔏", alias: ":lock_with_ink_pen:", name: "LOCK WITH INK PEN" },
    {
        emoji: "🔐",
        alias: ":closed_lock_with_key:",
        name: "CLOSED LOCK WITH KEY"
    },
    { emoji: "🔒", alias: ":lock:", name: "LOCK" },
    { emoji: "🔓", alias: ":unlock:", name: "OPEN LOCK" }
];

export default objects;
